### ISSUE TITLE
ModuleNotFoundError: No module named 'zotnote.application'

### ISSUE THREAD

**Issue by ripefig** [Bubblbu/zotnote#13]
```
> zotnote

Traceback (most recent call last):
  File "/home/username/.local/bin/zotnote", line 5, in <module>
    from zotnote.application import main
```
ModuleNotFoundError: No module named 'zotnote.application'

**Comment by Bubblbu** [comment]
Hi! First issue brought up by a user :tada: Time to celebrate that something's not working :D 

Which version did you install?

If you installed it some time ago, could you try updating it to the latest one on PyPI (https://pypi.org/project/zotnote/)?

**Comment by Bubblbu** [comment]
I've finally had time to address this bug with v0.3.5! Should be fixed and a good ol' fresh install from PyPI should resolve this issue.
